'''How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?'''

def answer(aMin, aMax, bMin, bMax):
    terms = []
    for a in range(aMin, aMax + 1):
        for b in range(bMin, bMax + 1):
            number = a ** b
            if number not in terms:
                terms.append(number)
    terms.sort()
    print(len(terms))

if __name__ == '__main__':
    answer(2, 100, 2, 100)