'Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:'
'1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...'
'By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'

def Fibonacci(maxIncl):
    numbers = [1, 2]
    i = 2
    value = 2
    while value <= maxIncl:
        value = numbers[i-1] + numbers[i-2]
        numbers.append(value)
        i = i + 1
    numbers.pop(-1)
    return(numbers)

def EvenFibonacciSum(maxIncl):
    numbers = Fibonacci(maxIncl)

    sumOfNumbers = 0
    for i in numbers:
        if (i % 2 == 0):
            sumOfNumbers = sumOfNumbers + i

    print(sumOfNumbers)


if __name__ == '__main__':
    EvenFibonacciSum(4000000)