'''Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
and D = |Pk - Pj| is minimised; what is the value of D?'''

def is_pentagonal(n):
    inverse_pentagonal = ((1 + 24 * n) ** (1/2) + 1) / 6
    return inverse_pentagonal == int(inverse_pentagonal)

def search():
    found = False
    i = 1
    while found == False:
        n = i * (3 * i - 1) / 2
        for j in range(i-1, 0, -1):
            m = j * (3 * j - 1) / 2
            if is_pentagonal(n - m) and is_pentagonal(m + n):
                print(n - m)
                found = True
        i += 1

if __name__ == '__main__':
    #print(generatePentagonalNumbers(10))
    #print(is_pentagonal(117))
    search()